# Generated by Django 4.0.2 on 2022-04-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='depot',
        ),
        migrations.CreateModel(
            name='DepotProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.depot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.product')),
            ],
        ),
    ]
