# Generated by Django 4.0.4 on 2022-06-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_truck_customer'),
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.depot')),
            ],
        ),
    ]
