# Generated by Django 4.0.2 on 2022-04-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_remove_product_depot_depotproduct'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='depot.depotproduct'),
        ),
    ]
