# Generated by Django 4.0.4 on 2022-05-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('depot', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=True)),
                ('is_loaded', models.BooleanField(default=True)),
                ('lpo_no', models.CharField(max_length=50, null=True)),
                ('order_no', models.CharField(max_length=50)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vol_obs', models.FloatField()),
                ('vol_20', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.depot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.truck')),
            ],
        ),
    ]
